# src/OC/PlatformBundle/Resources/config/routing.yml

vtc_platform_home:
    path:      /{page}
    defaults: { _controller: VTCAnnonceBundle:Advert:index, page: 1 }
    requirements:
        page: \d*

vtc_platform_view:
    path:      /advert/{id}
    defaults:  { _controller: VTCAnnonceBundle:Advert:view }
    requirements:
        id: \d+

vtc_platform_partager:
    path:      /advert/{id}
    defaults:  { _controller: VTCAnnonceBundle:Advert:partager }
    requirements:
        id: \d+

vtc_platform_searchresult:
    path:      /searchresult
    defaults:  { _controller: VTCAnnonceBundle:Advert:mysearch }
    requirements:
        id: \d+

vtc_platform_myaccount:
    path:      /myaccount
    defaults:  { _controller: VTCAnnonceBundle:Advert:account }
    requirements:
        id: \d+

vtc_platform_add:
    path:      /add
    defaults:  { _controller: VTCAnnonceBundle:Advert:add }

vtc_platform_edit:
    path:      /edit/{id}
    defaults:  { _controller: VTCAnnonceBundle:Advert:edit }
    requirements:
        id: \d+

vtc_platform_delete:
    path:      /delete/{id}
    defaults:  { _controller: VTCAnnonceBundle:Advert:delete }
    requirements:
        id: \d+

vtc_platform_contact:
    path:      /contact
    defaults:  { _controller: VTCAnnonceBundle:Advert:contact }

vtc_platform_deleteuser:
    path:      /deleteuser/{id}
    defaults:  { _controller: VTCAnnonceBundle:Advert:deleteuser }
    requirements:
        id: \d+

vtc_platform_admin:
    path:       /admin
    defaults: { _controller: VTCAnnonceBundle:Advert:admin }

vtc_platform_admin_userview:
    path:       /admin/userview/{id}
    defaults: { _controller: VTCAnnonceBundle:Advert:adminuserview }
    requirements:
        id: \d+

vtc_platform_admindeleteuser:
    path:       /admin/deleteuser/{id}
    defaults: { _controller: VTCAnnonceBundle:Advert:admindeleteuser }
    requirements:
        id: \d+


